#!/usr/bin/python
#
#  Copyright 2002-2024 Barcelona Supercomputing Center (www.bsc.es)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# -*- coding: utf-8 -*-

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import colmena.grpc.route_guide_pb2 as route__guide__pb2


class ColmenaPlatformStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Store = channel.unary_unary(
            "/ColmenaPlatform/Store",
            request_serializer=route__guide__pb2.StorageRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.GetStored = channel.unary_unary(
            "/ColmenaPlatform/GetStored",
            request_serializer=route__guide__pb2.GetStoredRequest.SerializeToString,
            response_deserializer=route__guide__pb2.GetStoredResponse.FromString,
        )
        self.Publish = channel.unary_unary(
            "/ColmenaPlatform/Publish",
            request_serializer=route__guide__pb2.StorageRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.Subscribe = channel.unary_stream(
            "/ColmenaPlatform/Subscribe",
            request_serializer=route__guide__pb2.GetStoredRequest.SerializeToString,
            response_deserializer=route__guide__pb2.GetStoredResponse.FromString,
        )
        self.GetSubscriptionItem = channel.unary_unary(
            "/ColmenaPlatform/GetSubscriptionItem",
            request_serializer=route__guide__pb2.GetStoredRequest.SerializeToString,
            response_deserializer=route__guide__pb2.GetStoredResponse.FromString,
        )
        self.StoreMetrics = channel.unary_unary(
            "/ColmenaPlatform/StoreMetrics",
            request_serializer=route__guide__pb2.MetricsStorageRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.QueryMetrics = channel.unary_unary(
            "/ColmenaPlatform/QueryMetrics",
            request_serializer=route__guide__pb2.MetricsQueryRequest.SerializeToString,
            response_deserializer=route__guide__pb2.MetricsQueryResponse.FromString,
        )
        self.GetAllServices = channel.unary_stream(
            "/ColmenaPlatform/GetAllServices",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=route__guide__pb2.ServiceDescription.FromString,
        )
        self.SubscribeToServiceChanges = channel.unary_stream(
            "/ColmenaPlatform/SubscribeToServiceChanges",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=route__guide__pb2.ServiceDescription.FromString,
        )
        self.AddService = channel.unary_unary(
            "/ColmenaPlatform/AddService",
            request_serializer=route__guide__pb2.ServiceDescription.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.RemoveService = channel.unary_unary(
            "/ColmenaPlatform/RemoveService",
            request_serializer=route__guide__pb2.ServiceDescriptionId.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class ColmenaPlatformServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStored(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSubscriptionItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StoreMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueryMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAllServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubscribeToServiceChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ColmenaPlatformServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Store": grpc.unary_unary_rpc_method_handler(
            servicer.Store,
            request_deserializer=route__guide__pb2.StorageRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "GetStored": grpc.unary_unary_rpc_method_handler(
            servicer.GetStored,
            request_deserializer=route__guide__pb2.GetStoredRequest.FromString,
            response_serializer=route__guide__pb2.GetStoredResponse.SerializeToString,
        ),
        "Publish": grpc.unary_unary_rpc_method_handler(
            servicer.Publish,
            request_deserializer=route__guide__pb2.StorageRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "Subscribe": grpc.unary_stream_rpc_method_handler(
            servicer.Subscribe,
            request_deserializer=route__guide__pb2.GetStoredRequest.FromString,
            response_serializer=route__guide__pb2.GetStoredResponse.SerializeToString,
        ),
        "GetSubscriptionItem": grpc.unary_unary_rpc_method_handler(
            servicer.GetSubscriptionItem,
            request_deserializer=route__guide__pb2.GetStoredRequest.FromString,
            response_serializer=route__guide__pb2.GetStoredResponse.SerializeToString,
        ),
        "StoreMetrics": grpc.unary_unary_rpc_method_handler(
            servicer.StoreMetrics,
            request_deserializer=route__guide__pb2.MetricsStorageRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "QueryMetrics": grpc.unary_unary_rpc_method_handler(
            servicer.QueryMetrics,
            request_deserializer=route__guide__pb2.MetricsQueryRequest.FromString,
            response_serializer=route__guide__pb2.MetricsQueryResponse.SerializeToString,
        ),
        "GetAllServices": grpc.unary_stream_rpc_method_handler(
            servicer.GetAllServices,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=route__guide__pb2.ServiceDescription.SerializeToString,
        ),
        "SubscribeToServiceChanges": grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeToServiceChanges,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=route__guide__pb2.ServiceDescription.SerializeToString,
        ),
        "AddService": grpc.unary_unary_rpc_method_handler(
            servicer.AddService,
            request_deserializer=route__guide__pb2.ServiceDescription.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "RemoveService": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveService,
            request_deserializer=route__guide__pb2.ServiceDescriptionId.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ColmenaPlatform", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ColmenaPlatform(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Store(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ColmenaPlatform/Store",
            route__guide__pb2.StorageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetStored(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ColmenaPlatform/GetStored",
            route__guide__pb2.GetStoredRequest.SerializeToString,
            route__guide__pb2.GetStoredResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Publish(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ColmenaPlatform/Publish",
            route__guide__pb2.StorageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Subscribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ColmenaPlatform/Subscribe",
            route__guide__pb2.GetStoredRequest.SerializeToString,
            route__guide__pb2.GetStoredResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetSubscriptionItem(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ColmenaPlatform/GetSubscriptionItem",
            route__guide__pb2.GetStoredRequest.SerializeToString,
            route__guide__pb2.GetStoredResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def StoreMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ColmenaPlatform/StoreMetrics",
            route__guide__pb2.MetricsStorageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def QueryMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ColmenaPlatform/QueryMetrics",
            route__guide__pb2.MetricsQueryRequest.SerializeToString,
            route__guide__pb2.MetricsQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetAllServices(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ColmenaPlatform/GetAllServices",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            route__guide__pb2.ServiceDescription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SubscribeToServiceChanges(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ColmenaPlatform/SubscribeToServiceChanges",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            route__guide__pb2.ServiceDescription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AddService(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ColmenaPlatform/AddService",
            route__guide__pb2.ServiceDescription.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RemoveService(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ColmenaPlatform/RemoveService",
            route__guide__pb2.ServiceDescriptionId.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
